### ISSUE TITLE
legacy BDS emulation: int server error 500

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/hpc-datastore#8]
`.spim.data.SpimDataIOException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:9080/bdv/a534ba9f-578d-49e9-8eb5-6f1e28ffe66e/1/`

when accessing newly added channel

as a result, the new channel cannot be opened in BDV

**Comment by xulman** [comment]
interestingly, when accessing via browser

it shows
`Internal Server Error java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerExceptionError id `
and prints totaly wrong ID under this message line

**Comment by kozusznik** [comment]
I solved the issue. It was caused by non-existent N5 blocks during thumbnail generation.

**Comment by xulman** [comment]
in the commit 6993bfa597b712 , is the empty array generated only for the thumbnails
or is it always the case that an empty array is returned for a block that is missing in the underlying N5 data?
'cause server was nicely reporting absence of missing chunks/blocks when downloading data (not thumbnails) and we would loose this now...

**Comment by xulman** [comment]
very good!
after testing, it does NOT submit fake-created blocks but instead, as wanted and thus correctly, it submits indicator of no-block-present

this is issue can now be closed for real :-)
